= The worm in ORM
Doc Writer <rogwara@nimworks.com>
v1
:hardbreaks:

== Introduction
nw.orm is a simple reusable library that takes away certain type of repetitive tasks while developing Java based software that interacts with databases. It encourages developers to focus on the actual project work, by removing these repetitive tasks. It is basically a wrapper around JPA that exposes classes and methods that are ideal for both Java SE and Java EE applications. The library is lightweight and does not enforce any design pattern.

== Quick Start
The project is split into modules that can be used independently, the idea here is to have a common interface across multiple datasource possibly including non relational databases

=== Installation
nw.orm binaries are hosted on maven central.

==== JPA
Ideal for projects that uses JPA from different providers like OpenJPA, Hibernate, and EclipseLink

[source, xml]
----
<dependency>
	<groupId>com.nimworks</groupId>
	<artifactId>nworm.core</artifactId>
	<version>${nworm.version}</version>
</dependency>
----

==== Hibernate Specific
Ideal for projects using hibernate core modules
----
<dependency>
	<groupId>com.nimworks</groupId>
	<artifactId>nworm.hibernate</artifactId>
	<version>${nworm.version}</version>
</dependency>
----

==== TODO

* MongoDB
* Elastic Search
* Cassandra

=== Code

nw.orm provides base classes for building entities. The base class provides and manages extra fields that can be useful. These fields include

* create_date: The entity create date
* last_updated: The last time the entity was updated
* deleted: soft deletion marker
* active: can be used to toggle rows as on or off

===== Base Classes

* IEntity
* REntity
* SEntity

The main differences is in how the primary keys are denoted



[source, java]
----
@Entity
@Table(name = "ACCESS_TOKEN")
public class AccessToken extends REntity {

	private static final long serialVersionUID = -5221279551618337736L;
}
----

Provide appropriate mappings

=== Querying

[source, java]
----
Nworm worm = Nworm.geInstance();
worm.getById(AccessToken.class, 1L);
----




